spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: msvc-orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2